// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type User struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string               `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type UsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersResponse) Reset()         { *m = UsersResponse{} }
func (m *UsersResponse) String() string { return proto.CompactTextString(m) }
func (*UsersResponse) ProtoMessage()    {}
func (*UsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{2}
}

func (m *UsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersResponse.Unmarshal(m, b)
}
func (m *UsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersResponse.Marshal(b, m, deterministic)
}
func (m *UsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersResponse.Merge(m, src)
}
func (m *UsersResponse) XXX_Size() int {
	return xxx_messageInfo_UsersResponse.Size(m)
}
func (m *UsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersResponse proto.InternalMessageInfo

func (m *UsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type Project struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{3}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type ProjectsResponse struct {
	Projects             []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProjectsResponse) Reset()         { *m = ProjectsResponse{} }
func (m *ProjectsResponse) String() string { return proto.CompactTextString(m) }
func (*ProjectsResponse) ProtoMessage()    {}
func (*ProjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{4}
}

func (m *ProjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectsResponse.Unmarshal(m, b)
}
func (m *ProjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectsResponse.Marshal(b, m, deterministic)
}
func (m *ProjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectsResponse.Merge(m, src)
}
func (m *ProjectsResponse) XXX_Size() int {
	return xxx_messageInfo_ProjectsResponse.Size(m)
}
func (m *ProjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectsResponse proto.InternalMessageInfo

func (m *ProjectsResponse) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*UsersResponse)(nil), "pb.UsersResponse")
	proto.RegisterType((*Project)(nil), "pb.Project")
	proto.RegisterType((*ProjectsResponse)(nil), "pb.ProjectsResponse")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor_f80abaa17e25ccc8) }

var fileDescriptor_f80abaa17e25ccc8 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0xc1, 0x4b, 0xfb, 0x30,
	0x1c, 0xc5, 0x7f, 0xed, 0xd6, 0xdf, 0x9a, 0x6f, 0x55, 0x34, 0xec, 0x50, 0x26, 0xea, 0xe8, 0xc5,
	0x81, 0x90, 0x61, 0x3d, 0x89, 0xa7, 0x1d, 0x76, 0x53, 0x91, 0xaa, 0x78, 0x1c, 0xa9, 0xcd, 0x66,
	0xa4, 0x59, 0x42, 0x93, 0x82, 0xfe, 0x3d, 0xfe, 0xa3, 0x92, 0xb4, 0x9d, 0x05, 0x8f, 0xde, 0xda,
	0xf7, 0xde, 0x97, 0xf7, 0x79, 0x04, 0x42, 0x95, 0x13, 0x55, 0x49, 0x23, 0xb1, 0xaf, 0xf2, 0xc9,
	0xd9, 0x46, 0xca, 0x4d, 0xc9, 0xe6, 0x4e, 0xc9, 0xeb, 0xf5, 0xdc, 0x70, 0xc1, 0xb4, 0xa1, 0x42,
	0x35, 0xa1, 0x64, 0x04, 0xc1, 0x52, 0x28, 0xf3, 0x99, 0x7c, 0x79, 0x30, 0x7c, 0xd6, 0xac, 0xc2,
	0x07, 0xe0, 0xf3, 0x22, 0xf6, 0xa6, 0xde, 0x0c, 0x65, 0x3e, 0x2f, 0xf0, 0x09, 0xc0, 0x9a, 0x57,
	0xda, 0xac, 0xb6, 0x54, 0xb0, 0xd8, 0x77, 0x3a, 0x72, 0xca, 0x3d, 0x15, 0x0c, 0x1f, 0x03, 0x2a,
	0x69, 0xe7, 0x0e, 0x9c, 0x1b, 0x5a, 0xc1, 0x99, 0x63, 0x08, 0x98, 0xa0, 0xbc, 0x8c, 0x87, 0xce,
	0x68, 0x7e, 0xf0, 0x35, 0x40, 0xad, 0x0a, 0x6a, 0x58, 0xb1, 0xa2, 0x26, 0x0e, 0xa6, 0xde, 0x2c,
	0x4a, 0x27, 0xa4, 0x21, 0x25, 0x1d, 0x29, 0x79, 0xea, 0x48, 0x33, 0xd4, 0xa6, 0x17, 0x26, 0x99,
	0xc3, 0xbe, 0x85, 0xd4, 0x19, 0xd3, 0x4a, 0x6e, 0x35, 0xc3, 0xa7, 0x10, 0xd4, 0x56, 0x88, 0xbd,
	0xe9, 0x60, 0x16, 0xa5, 0x21, 0x51, 0x39, 0xb1, 0x89, 0xac, 0x91, 0x93, 0x37, 0x18, 0x3d, 0x54,
	0xf2, 0x9d, 0xbd, 0x9a, 0x5f, 0xc3, 0x30, 0x0c, 0x7b, 0x93, 0xdc, 0xf7, 0x5f, 0xd0, 0x6e, 0xe0,
	0xb0, 0x6d, 0xfa, 0xa1, 0x3b, 0x87, 0x50, 0xb5, 0x5a, 0x0b, 0x18, 0x59, 0xc0, 0x36, 0x97, 0xed,
	0xcc, 0x54, 0x40, 0xf4, 0xb2, 0x78, 0xbc, 0x5b, 0x7e, 0x50, 0xa1, 0x4a, 0x86, 0x2f, 0x00, 0xdd,
	0x72, 0x6d, 0xdc, 0x54, 0x8c, 0xec, 0x89, 0x7b, 0xa4, 0xc9, 0x51, 0x37, 0x6f, 0x57, 0x91, 0xfc,
	0xc3, 0x97, 0xb0, 0x67, 0xc3, 0x5d, 0x79, 0x3f, 0x3f, 0xee, 0xb5, 0xf5, 0x4e, 0xf2, 0xff, 0x6e,
	0xca, 0xd5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xad, 0xd6, 0x9d, 0xbc, 0x2d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WASMExampleClient is the client API for WASMExample service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WASMExampleClient interface {
	ListUsers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UsersResponse, error)
	ListProjects(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProjectsResponse, error)
}

type wASMExampleClient struct {
	cc *grpc.ClientConn
}

func NewWASMExampleClient(cc *grpc.ClientConn) WASMExampleClient {
	return &wASMExampleClient{cc}
}

func (c *wASMExampleClient) ListUsers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UsersResponse, error) {
	out := new(UsersResponse)
	err := c.cc.Invoke(ctx, "/pb.WASMExample/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wASMExampleClient) ListProjects(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProjectsResponse, error) {
	out := new(ProjectsResponse)
	err := c.cc.Invoke(ctx, "/pb.WASMExample/ListProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WASMExampleServer is the server API for WASMExample service.
type WASMExampleServer interface {
	ListUsers(context.Context, *Empty) (*UsersResponse, error)
	ListProjects(context.Context, *Empty) (*ProjectsResponse, error)
}

// UnimplementedWASMExampleServer can be embedded to have forward compatible implementations.
type UnimplementedWASMExampleServer struct {
}

func (*UnimplementedWASMExampleServer) ListUsers(ctx context.Context, req *Empty) (*UsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (*UnimplementedWASMExampleServer) ListProjects(ctx context.Context, req *Empty) (*ProjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProjects not implemented")
}

func RegisterWASMExampleServer(s *grpc.Server, srv WASMExampleServer) {
	s.RegisterService(&_WASMExample_serviceDesc, srv)
}

func _WASMExample_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WASMExampleServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WASMExample/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WASMExampleServer).ListUsers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WASMExample_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WASMExampleServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.WASMExample/ListProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WASMExampleServer).ListProjects(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _WASMExample_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.WASMExample",
	HandlerType: (*WASMExampleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUsers",
			Handler:    _WASMExample_ListUsers_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _WASMExample_ListProjects_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb.proto",
}
